version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: microcentros-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: microcentros
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
